apiVersion: keda.sh/v1alpha1
kind: ScaledObject

metadata:
  name: sqs-scaler
  namespace: autoscaling

spec:

  scaleTargetRef:
    name: worker

  minReplicaCount: 0

  maxReplicaCount: 10

  pollingInterval: 15

  cooldownPeriod: 30

  triggers:

  - type: aws-sqs-queue

    authenticationRef:
      name: aws-trigger-auth

    metadata:

      queueURL: https://sqs.us-east-1.amazonaws.com/497508796460/autoscaling

      queueLength: "5"

      awsRegion: us-east-1
