apiVersion: v1
kind: ResourceQuota

metadata:
  name: team-quota
  namespace: quota-demo

spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi

    limits.cpu: "2"
    limits.memory: 2Gi

    pods: "5"

    services: "3"

    persistentvolumeclaims: "2"
