apiVersion: v1
kind: Pod
metadata:
  name: vault-test
  namespace: default
spec:
  serviceAccountName: myapp
  containers:
  - name: ubuntu
    image: ubuntu:24.04
    command:
    - sleep
    - "3600"
