apiVersion: v1
kind: Pod
metadata:
  name: vault-inject-demo
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "myapp-role"
    vault.hashicorp.com/agent-inject-secret-config.txt: "secret/data/myapp"
spec:
  serviceAccountName: myapp

  containers:
  - name: app
    image: ubuntu:24.04
    command:
      - sleep
      - "3600"
