apiVersion: apps/v1
kind: Deployment

metadata:
  name: vpa-demo
  namespace: autoscaling

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vpa-demo

  template:

    metadata:
      labels:
        app: vpa-demo

    spec:

      containers:

      - name: stress

        image: polinux/stress

        command:

        - stress

        args:

        - "--vm"

        - "1"

        - "--vm-bytes"

        - "200M"

        - "--vm-hang"

        - "1"

        resources:

          requests:

            cpu: 100m

            memory: 100Mi

          limits:

            cpu: 500m

            memory: 500Mi
