
# Builder Stage
FROM golang:1.26 AS builder

WORKDIR /app

# Copy dependency files first
COPY go.mod .
COPY go.sum .

# Cache downloaded Go modules
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

# Copy application source
COPY . .

# Cache Go build artifacts
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -o server .

# Runtime Stage
FROM gcr.io/distroless/static-debian12

WORKDIR /

COPY --from=builder /app/server /server

USER nonroot:nonroot

EXPOSE 8080

ENTRYPOINT ["/server"]
