global:
  enabled: true

server:
  enabled: true

  replicas: 3

  image:
    repository: hashicorp/vault
    tag: "1.20.3"

  resources:
    requests:
      cpu: 250m
      memory: 512Mi

    limits:
      cpu: 500m
      memory: 1Gi

  dataStorage:
    enabled: true

    size: 10Gi

    storageClass: gp2

  ha:
    enabled: true

    raft:
      enabled: true

      config: |
        ui = true

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = 1
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

ui:
  enabled: true

  serviceType: ClusterIP
