apiVersion: v1
kind: Pod

metadata:
  name: above-max
  namespace: resource-demo

spec:
  containers:
  - name: nginx
    image: nginx:latest

    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
