apiVersion: v1
kind: Pod

metadata:
  name: below-min
  namespace: resource-demo

spec:
  containers:
  - name: nginx
    image: nginx:latest

    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
