apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: usecase-16-batchjob-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
