apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: operator-lab
  region: ap-south-1

managedNodeGroups:
  - name: operator-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
